[project]
name = "delugerpg-bot"
version = "0.1.0"
description = "TOS-compliant scaffold for a DelugeRPG bot framework"
authors = [{ name = "Your Name" }]
requires-python = ">=3.10"
readme = "README.md"

[tool.pytest.ini_options]
addopts = "-q"